#!/bin/bash
# The measurement ladder: stock -> configuration only -> configuration + Lumen.
#
#   ladder.sh qwen      # Qwen-Image 1024 online training      (10 rungs)
#   ladder.sh wan       # Wan2.1 81x368x544 online training     (10 rungs)
#   ladder.sh wanemb    # Wan2.1 offline_embedding              (6 rungs)
#   ladder.sh offline   # optional offline-embedding workflow   (see below)
#   ladder.sh qwen A0 B3 L7    # only these rungs
#
# Each rung adds one change to the rung before it, so each row of the result is
# the increment of one change on top of everything above it. Rungs A0..B* touch
# only VeOmni configuration (CLI overrides of the example yaml); rungs L* keep
# the best configuration and add Lumen, one LUMEN_PATCH entry at a time.
#
# REPS (default "r1 r2 r3") repeats are run round by round -- every rung once,
# then every rung again -- so slow drift in the machine lands on all rungs
# alike instead of on whichever ran last. Summarise with
#   summarize.py --control pvq-A0 --chain -- pvq-A0 pvq-B1 ...   (the command is printed)
#
# DRY_RUN=1 prints the commands without running them. Do not edit this file
# while it runs: bash reads a script as it executes it.
set -o pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$HERE/env.sh"

WHICH="${1:?usage: ladder.sh <qwen|wan|wanemb|offline> [rung ...]}"
shift
REPS="${REPS:-r1 r2 r3}"

EC="--train.empty_cache_steps 500"
NOGC="--train.gradient_checkpointing.enable false"
NORESHARD="--train.accelerator.fsdp_config.reshard_after_forward false"
LOADER="--data.dataloader.num_workers 2 --data.dataloader.pin_memory true"

# name | LUMEN_PATCH | VeOmni overrides
case "$WHICH" in
    qwen)
        RUNNER="$HERE/run_10steps.sh"; PREFIX=pvq; TASK_ENV=""
        B="$EC $NOGC $NORESHARD"
        RUNGS=(
            "A0||"
            "B1||$EC"
            "B2||$EC $NOGC"
            "B3||$B"
            "L1|vae_bf16|$B"
            "L2|vae_bf16,vae_conv|$B"
            "L4|vae_bf16,vae_conv,sdpa_efficient|$B"
            "L5|vae_bf16,vae_conv,sdpa_efficient,attn_triton_fwd|$B"
            "L6|vae_bf16,vae_conv,sdpa_efficient,attn_triton_fwd,rmsnorm_fuse|$B"
            "L7|vae_bf16,vae_conv,sdpa_efficient,attn_triton_fwd,rmsnorm_fuse,local_adamw|$B"
        )
        ;;
    wan)
        RUNNER="$HERE/run_wan_10steps.sh"; PREFIX=pvw; TASK_ENV="WAN_TASK=online_training"
        B="$EC $NOGC $LOADER"
        RUNGS=(
            "A0||"
            "B1||$EC"
            "B2||$EC $NOGC"
            "B4||$B"
            "L1|vae_bf16|$B"
            "L2|vae_bf16,vae_conv_video|$B"
            "L3|vae_bf16,vae_conv_video,conv_pad_in_kernel|$B"
            "L4|vae_bf16,vae_conv_video,conv_pad_in_kernel,sdpa_efficient|$B"
            "L5|vae_bf16,vae_conv_video,conv_pad_in_kernel,sdpa_efficient,attn_triton_fwd|$B"
            "L7|vae_bf16,vae_conv_video,conv_pad_in_kernel,sdpa_efficient,attn_triton_fwd,local_adamw|$B"
        )
        ;;
    wanemb)
        RUNNER="$HERE/run_wan_10steps.sh"; PREFIX=pvwe; TASK_ENV="WAN_TASK=offline_embedding"
        B="$EC $LOADER"
        RUNGS=(
            "A0||"
            "B1||$EC"
            "B4||$B"
            "L1|vae_bf16|$B"
            "L2|vae_bf16,vae_conv_video|$B"
            "L3|vae_bf16,vae_conv_video,conv_pad_in_kernel|$B"
        )
        ;;
    offline)
        # The alternative workflow: embed once (VAE + text encoder, no DiT),
        # then train from the stored embeddings. The embedding runs with the
        # Lumen rung's VAE settings; training reads the r1 embedding, so the
        # embed rung is listed first. Wan's embedding is the wanemb ladder's L3
        # r1 run, so run that ladder before this one. Training loads no VAE,
        # hence no VAE patch; Qwen needs qwen_offline_fix instead (VeOmni
        # 573848a crashes on its first step without it).
        QE="$OUT_DIR/embed-pvoq-emb-r1"
        WE="$OUT_DIR/embed-pvwe-L3-r1"
        QL="$EC $NOGC $NORESHARD"
        WL="$EC $NOGC $LOADER"
        RUNGS=(
            "q:emb|vae_bf16,vae_conv|$EC --train.training_task offline_embedding --data.offline_embedding_save_dir @EMBED@"
            "q:train|sdpa_efficient,attn_triton_fwd,rmsnorm_fuse,local_adamw,qwen_offline_fix|$QL --train.training_task offline_training --data.train_path $QE"
            "w:train|sdpa_efficient,attn_triton_fwd,local_adamw|$WL --train.training_task offline_training --data.train_path $WE"
        )
        ;;
    *) echo "unknown ladder: $WHICH (qwen|wan|wanemb|offline)" >&2; exit 2 ;;
esac

ONLY=("$@")
want() {
    [ ${#ONLY[@]} -eq 0 ] && return 0
    local r
    for r in "${ONLY[@]}"; do [ "$r" = "$1" ] && return 0; done
    return 1
}

run_one() {  # <run name> <suffix> <patch> <runner> <task env> <overrides...>
    local name="$1" rep="$2" patch="$3" runner="$4" task_env="$5"
    shift 5
    local cmd=(env RUN_NAME="$name" RUN_SUFFIX="$rep" LUMEN_PATCH="$patch")
    [ -n "$task_env" ] && cmd+=("$task_env")
    cmd+=(bash "$runner" custom "$@")
    echo ">>> $(date -Is) ${cmd[*]}"
    [ "${DRY_RUN:-0}" = "1" ] && return 0
    "${cmd[@]}" >"$LOG_DIR/$name-$rep.stdout" 2>&1
    local rc=$?
    echo "<<< $(date -Is) $name-$rep rc=$rc"
    return $rc
}

NAMES=()
for rep in $REPS; do
    for spec in "${RUNGS[@]}"; do
        IFS='|' read -r rung patch overrides <<<"$spec"
        want "$rung" || continue
        if [ "$WHICH" = offline ]; then
            model="${rung%%:*}"; kind="${rung##*:}"
            name="pvo$model-$kind"
            if [ "$model" = q ]; then runner="$HERE/run_10steps.sh"; else runner="$HERE/run_wan_10steps.sh"; fi
            tenv=""
            overrides="${overrides//@EMBED@/$OUT_DIR/embed-$name-$rep}"
        else
            name="$PREFIX-$rung"; runner="$RUNNER"; tenv="$TASK_ENV"
        fi
        # shellcheck disable=SC2086  # overrides are whitespace-separated flags by design
        run_one "$name" "$rep" "$patch" "$runner" "$tenv" $overrides || echo "!!! $name-$rep failed; continuing"
        [[ " ${NAMES[*]} " == *" $name "* ]] || NAMES+=("$name")
    done
done

echo
echo "summarise with:"
echo "  python $HERE/summarize.py --control ${NAMES[0]} --chain --reps $REPS -- ${NAMES[*]}"
